apiVersion: v1
kind: Pod
metadata:
  name: multi-container-shared-pod
  labels:
    app: multi-container
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: nginx-web
      image: nginx
      ports:
      - containerPort: 30000
        name: web-service
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
    - name: debian-sidecar
      image: debian
      volumeMounts:
        - name: shared-data
          mountPath: /data
      command: ["/bin/sh"]
      args: ["-c", "trap : TERM INT; sleep infinity && wait"]
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-service
spec:
  type: NodePort
  selector:
    app: multi-container
  ports:
  - protocol: TCP
    port: 80
    targetPort: web-service